#!/bin/bash

SCRIPT_DIR=$(dirname $(realpath "$0"))

cd "$SCRIPT_DIR/example_script"

echo "Python3-Version: >>>>"

python3 --version

echo "<<<<<<<<<<<<<<<<<<<<<"

python3 example.py slimer.png

exit_code=$?

if [[ -e model.h5 ]]; then
	rm -f model.h5
else
	echo "model.h5 not found!"
	exit 1
fi

echo "exit_code: $exit_code"

exit $exit_code
