#!/bin/bash

if ! [[ -d env ]]; then
	python3 -mvenv env
	source env/bin/activate

	pip install pylint flake8

	pip install -r requirements.txt
fi

source env/bin/activate

pylint asanai.py

flake8 asanai.py
