#!/bin/bash

if ! [[ -d env ]]; then
	python3 -mvenv env
	source env/bin/activate

	pip install pylint pyflakes

	pip install -r requirements.txt
fi

source env/bin/activate

if ! pylint asanai.py; then
	echo "pylint asanai.py failed. Exiting."
	exit 1
fi


if ! pyflakes asanai.py; then
	echo "pyflakes asanai.py failed. Exiting"
	exit 2
fi

exit 0
